version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    container_name: respectroom-nginx
    volumes:
      - ./:/var/www/html
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/sites/:/etc/nginx/sites-available
      - .docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - database
      - php
    ports:
      - "8080:80"
    networks:
      - respectroom

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: respectroom-php
    environment:
      TZ: Europe/Prague
    volumes:
      - ./:/var/www/html
      - .docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.dev.ini
    depends_on:
      - database
    networks:
      - respectroom

  adminer:
    image: dockette/adminer:dg
    container_name: respectroom-adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8000:80"
    networks:
      - respectroom

  database:
    image: mariadb:10.8.2
    container_name: respectroom-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: respectroom
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      TZ: Europe/Prague
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - respectroom

networks:
  respectroom:

volumes:
  db-data:
